= dotfiles

:toc:
:toclevels: 1

== Overview

My cross-platform dotfiles (works on MacOS/Windows) that configures ZSH and neovim. 

== Pre-Requisites: Needs Manual Setup 


=== MacOS 
- Install link:Homebrew[https://brew.sh/]



=== Windows - WSL
- Install link:https://chocolatey.org/[Chocolatey], the fantastic windows package manager for software.
- link:https://learn.microsoft.com/en-us/windows/wsl/install[Install WSL - Windows Subsystem for Linux]
- Download  link:https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip[Jetbrains Mono Nerdfonts]
- Extract the downloaded zip into a folder, open the folde in Windows Explorer, select all fonts in the folder, right-click and click `Install`
- To use the JetbrainsMono Nerd Font in our Windows Terminal:
    ** Open up Settings ctrl ,
    ** Open the tray by clicking the three-lines icon on the top left
    ** Click Ubuntu under Profiles to open its profile settings
    ** Scroll down to Additional Settings and click Appearance
    ** Change Font face to JetBrainsMono Nerd Font


== Checkout project and Run Setup Script
Open a bash shell and execute the following commands:
[source,shell]
----
curl -sfL https://raw.github.com/lenkite/dotfiles/master/setup.sh | bash
----


== Customize Path and Environment Variables

=== Personal environment variables
Create optional file `~.env`. This is sourced by `~/.zshenv` . You should
put environment variable definitions here apart from those affecting the `PATH`

=== Personal additions to PATH 
Create optional file `~/.paths`. This file is loaded and every line is assumed to be a valid path and is 
added to the `PATH` environment variable.

=== Personal ZSH configuration
Create optional file `~/my.zsh`. Personal configuration can be added here.
This file is sourced by `~/.zshrc` at the end.

== autorun Cotributions
Put your contributions with a `.zsh' extension in `dotfiles/zshcfg/autorun`. These will be sourced by `zshrc`.

== Setup of neovim, SDK and Utilities 
This section assumes you have successfully run `setup.sh` once as described earlier. Enter fresh shell instance:
----
cd ~/dotfiles
./setup.sh -v  # For neovim setup (recreates symlinks)
./setup.sh -s  # For SDK's
# Now Exit and Relaunch your Shell
./setup.sh -u  # For utilities tools
----

== Setup For Coding 
TODO: not yet implementation
single stop config for neovim, Intellij and vscode
Enter fresh shell instance and `cd ~/dotfiles && ./setup.sh -c`

== Keyboard Shortscuts

See link:shortcuts.md[Keyboard Shortcuts]
