= dotfiles

My new dotfiles that leverages the non-VIM portions of YADR dotfiles. The ZSH and other configurations of YADR `https://github.com/skwp/dotfiles` are great. The VIM portions are too heavyweight and most unforgivably YARD hard-codes the leader key to ',' explicitly in all its keybindings  which makes it a no-go for me. I use SPACE as the leader key. 
Also contains settings for Intellij Idea for OSX and Windows.

== Setup

=== ZSH Setup
* Install YADR with the following command.
----
sh -c "`curl -fsSL https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh`" -s ask
----
* Check out dotfiles to your home directory
----
cd ~
git clone https://github.com/lenkite/dotfiles.git
----
* Then link `~/.zsh.after` to `dotfiles/zsh-after`, so we can override and fix YADR zsh.
----
rm -rf ~/.zsh.after
ln -s ~/dotfiles/zsh-after ~/.zsh.after
----

=== Notes
* Note that after doing the above you can put your custom zsh files in `~/.zsh.after` and they will be run automatically at shell startup. 

=== YADR ZSH  customizations

TODO fill me up later


=== VIM Setup
* Install the _Ultimate VIM Distribution_ following instructions at http://vim.spf13.com/#install

=== Spacemacs Setup
* Spacemacs is emacs with VIM wizardry and the space leader key
* See  http://spacemacs.org/
* `brew cask install emacs`
* Install Spacemacs:
 ** `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
 ** Launch emacs (Make sure your internet connection is working)
* Link all my private layers
----
find ~/dotfiles/spacemacs-layers -depth 1 -type d -exec ln -s '{}' ~/.emacs.d/private \;
----

== Common Editor Shortcuts Table


