= dotfiles

:toc:
:toclevels: 1

== Overview

My cross-platform dotfiles (works on MacOS/Windows) that configures ZSH and neovim. 

== Pre-Requisites: Needs Manual Setup 

=== MacOS 
- Install link:Homebrew[https://brew.sh/]
- Install ZSH `brew install zsh zsh-completions`

=== Windows
- Install link:https://chocolatey.org/[Chocolatey], the fantastic windows package manager for software.
- If you are on Windows 10 with at-least the Creators Update please install the https://msdn.microsoft.com/commandline/wsl["Windows Subsystem for Linux"] which is also called by the terrible name of "Bash on Ubuntu on Windows". Refer to the https://msdn.microsoft.com/en-us/commandline/wsl/install_guide[Installation Guide]. 
- After installing WSL, install wsltty for a better console: https://github.com/mintty/wsltty


== Run Setup Script
Open a shell and execute the following command:
.Execute this
[source,shell]
----
curl -sfL  https://raw.github.com/lenkite/dotfiles/master/setup.sh | bash
----


== Customize Path and Environment Variables

=== Personal environment variables
Create optional file `~.env`. This is sourced by `~/.zshenv` . You should
put environment variable definitions here apart from those affecting the `PATH`

=== Personal additions to PATH 
Create optional file `~/.paths`. This file is loaded and every line is assumed to be a valid path and is 
added to the `PATH` environment variable.

=== Personal ZSH configuration
Create optional file `~/my.zsh`. Personal configuration can be added here.
This file is sourced by `~/.zshrc` at the end.

== autorun Cotributions
Put your contributions with a `.zsh' extension in `dotfiles/zshcfg/autorun`. These will be sourced by `zshrc`.

== Setup of neovim, SDK and Utilities 
Enter fresh shell instance
----
./setup.sh -v  # For neovim setup (recreates symlinks)
./setup.sh -s  # For SDK's
# Now Exit and Relaunch your Shell
./setup.sh -u  # For utilities tools
----

== Setup For Coding 
TODO: not yet implementation
single stop config for neovim, Intellij and vscode
Enter fresh shell instance and `cd ~/dotfiles && ./setup.sh -c`

== Keyboard Shortscuts

See link:shortcuts.md[Keyboard Shortcuts]
