" vim: set sw=2 ts=2 sts=2 et tw=80 foldmarker={,} foldlevel=1 foldmethod=marker spell:

" NOTE {
"   Tarun Ramakrishna Elankath's vimrc file. Been using VIM for 12 years now. 
"   Re-created from scratch on Aug 20, 2011
"   Re-created from scratch again on Aug 6, 2016, taking the best parts from YADR
"   Extensively modified in period Aug, 2017
"   https://github.com/lenkite/dotfiles
" }

" { * Prelude: Encoding, Modeline Settings
"https://stackoverflow.com/questions/18321538/vim-error-e474-invalid-argument-listchars-tab-trail
scriptencoding utf-8
set encoding=utf-8
set modeline
set modelines=1
" }

" GUI VIM Config {

if has('gui')
  if has('win32')
    set guifont=Consolas:h11:cANSI:qDRAFT
  endif
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar
elseif has('nvim')
  let g:impact_transbg=1
  "au BufEnter * if &buftype == 'terminal' | :startinsert | endif # this sucks
endif
" }

"{ * History, Buffers, Undo
set history=10000               " Store lots of :cmdline history
set autowrite                  " Writes contents of file on next rewind last first make etc
"}
"

"{ * Turn Off Swap Files And Backups 
set noswapfile
set nobackup
set nowb
"}

" { * Indentation 
set autoindent
set smartindent
set smarttab
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0 nosmarttab "Make files need a Tab!
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
"}

" { * Screen Related
"
" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·
set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points
set visualbell noerrorbells t_vb= "
set lazyredraw " redraw only when we need to
" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set number                     " Line numbers are good
set relativenumber             " Relative line numbers are better but cause SLOW SCROLLING :(
set hidden
set wmh=0                      " Set winminheight to 0 so that
                               " maximizing a window collapses all other windows
set gcr=a:blinkon0             " Disable cursor blink
set showcmd                    " Show incomplete cmds down the bottom

"}

"{ * Folds 
""
" set foldnestmax=1       "deepest fold is 2 levels
" set foldlevel=0
" }



 " * { Syntax, Spelling and Completion 
syntax on
set synmaxcol=2048        "long lines are slow
filetype plugin on
filetype indent on
 " "http://vim.wikia.com/wiki/Great_wildmode/wildmenu_and_console_mouse
let g:skip_loading_mswin=1
 
set wildmode=list:longest,full
set wildmenu "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.swp,*.bak,*.pyc,*.class,*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif
set wildignore+=.idea/**

set spelllang=en
set spellfile=~/dotfiles/spell/en.utf-8.add

" suppress the annoying 'match x of y', 'The only match' and 'Pattern not found' messages
set shortmess+=c
    " IMPORTANTE: :help Ncm2PopupOpen for more information
    set completeopt=noinsert,menuone,noselect
"} 

" { * Clipboard
"https://stackoverflow.com/questions/30691466/what-is-difference-between-vims-clipboard-unnamed-and-unnamedplus-settings
" set clipboard^=unnamed
" }


" { * Scrolling 
set scrolloff=6         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=8
set sidescroll=1
" }

" { * Search 
 set hlsearch        " Highlight searches by default
 set ignorecase      " Ignore case when searching...
 set smartcase       " ...unless we type a capital
" }


" { * Matchit and Parenthesis
if filereadable(expand("$VIMRUNTIME/macros/matchit.vim"))
  source $VIMRUNTIME/macros/matchit.vim
endif
set matchtime=1 "time in tenths of a second to show the matching parenthesis
set showmatch "The vim implementation of matching parenthesis sucks
let loaded_matchparen = 1 "Parenthesis highlight is distracting like hell!
"}


" { * Autoreload vimrc
autocmd! bufwritepost vimrc source %
" }
