# See ZSH startup files: http://zsh.sourceforge.net/Intro/intro_3.html
# Link this to ~/.zshenv
# .zshenv is sourced on all invocations.
# All env variables including path should be set here.
# Should not produce output or aassume that shell is attached to tty.

[ -d ~/dotfiles ] && export dotfiles=~/dotfiles || echo "Could not locate dotfiles at ~/dotfiles"

# Autoloads 
# See https://unix.stackexchange.com/questions/33255/how-to-define-and-load-your-own-shell-function-in-zsh
#fpath=($dotfiles/zshcfg/zfuncs $fpath)
#autoload -Uz detect_os determine_user

source $dotfiles/zshcfg/zfuncs/os-user-detect.zsh


main() {
  detect_os
  detect_user
  load_dotenv
  load_dotpaths

  manpath=`manpath`
  manpath=(
    "$dotfiles/man"
    "$manpath[@]"
  )
  typeset -U manpath
  export MANPATH
}



# Source ~/.env. ~/.env should export user/system
# specific environment variables
load_dotenv() {
  envfile=~/.env
  [[ -f $envfile ]] && source $envfile
}

# Loads lines from ~/.paths and adds each line as 
# path component to env PATH 
load_dotpaths() {
  # http://zsh.sourceforge.net/Guide/zshguide02.html#l24
  typeset -U path
  path+=( $dotfiles/scripts ~/bin )
  pathsf=~/.paths
  if [[ -f $pathsf ]]; then
    #http://stackoverflow.com/questions/12651355/zsh-read-lines-from-file-into-array
    zmodload zsh/mapfile
    FLINES=( "${(f)mapfile[$pathsf]}" )
    LIST="${mapfile[$pathsf]}" # Not required unless stuff uses it
    integer POS=1             # Not required unless stuff uses it
    integer SIZE=$#FLINES     # Number of lines, not required unless stuff uses it
    # setting path list sets PATH in zsh
    path+=( $FLINES )
  fi
}

main

