#!/bin/bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

function main {
  echo "NOTE: script uses cf cli. Ensure you are logged into right CPI system and TENANT_NAME is set and optionally CO_APP_NAME if not it-co"
  check_deps
  coAppName=${CO_APP_NAME:-it-co}
  tenantName=${TENANT_NAME} || die "Please set TENANT_NAME"
  coAppGuid=$(cf app --guid $coAppName)
  echo "coAppGuid: $coAppGuid"
  echo "-Getting co app env..."
  coEnv=$(cf curl /v3/apps/$coAppGuid/env)
  # echo "-coEnv: $coEnv"
  imCreds=$(echo $coEnv | jq -r '.system_env_json.VCAP_SERVICES["managed-objectstore"][0].credentials')
  echo "imCreds: $imCreds"
  imUser=$(echo $imCreds | jq -r '.user')
  imPass=$(echo $imCreds | jq -r '.password')
  managedInstanceUrl=$(echo $imCreds | jq -r '.get_managed_instance_url')
  managedInstanceUrl=${managedInstanceUrl/\{tenant_id\}/$tenantName}
  # clientid=$(echo $clientCreds | jq -r '.clientid')
  echo "-imUser: $imUser"
  echo "-imPass: $imPass"
  echo "-managedInstanceUrl: $managedInstanceUrl"
  managedInstanceCreds=$(curl -s -u "$imUser:$imPass" $managedInstanceUrl) || die "Cannot reach $managedInstanceUrl"
  echo $managedInstanceCreds | jq '.'
  # clientsecret=$(echo $clientCreds | jq -r '.clientsecret')
  # echo "-clientsecret: $clientsecret"
}


function check_deps {
  deps=(cf jq curl)
  for dep in "${deps[@]}"; do
    installed "${dep}" || die "Missing '${dep}'"
  done
  echo "-check_deps OK."
}

function installed {
  cmd=$(command -v "${1}")

  [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
  return ${?}
}


function die {
  >&2 echo "Fatal: ${@}"
  exit 1
}

main
